version: "3"
services:
  meroedu-backend:
    container_name: meroedu-backend
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 9090:9090
    depends_on:
      - mysql
    volumes:
      - ./:/app
      - ./config.json:/app/config.json

  # live-reloader:
  #       image: apogiatzis/livereloading
  #       container_name: livereloader
  #       privileged: true
  #       depends_on:
  #         - mysql
  #       environment:
  #         - RELOAD_DELAY=1.5              # seconds
  #         - RELOAD_CONTAINER=meroedu-backend
  #       volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock
  #         - ./:/app
  mysql:
    image: mysql:5.7 
    container_name: meroedu-mysql
    command: mysqld --user=root
    volumes:
      - ./course.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=course
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot",  "--password=root"]
      timeout: 5s
      retries: 10